### ISSUE TITLE
Childchain relayer service

### ISSUE THREAD

**Issue by mwaa** [leapdao/nervos#26]
# Bounty
Listener and handler functionalities to relay transactions in the child-chains

## Scope

-  Handler function that receives lock events from CKB relayer service
-  Collect validator signatures via contract method collectLock
-  Listen for burn/unlock events on childchain
-  Once a burn occurs trigger validator signing
-  Collect the validator signature via contract method collectUnlock
-  Listen for the BurnQuorum event
-  Send BurnQuorum  event data to CKB relayer service
-  Use same json file to configure environment for both relayer services
> listener sleep time
> url endpoints for child chain
> url endpoints for ckb relayer service
> current chain mainent/testnet
> bridge script hash
> etc

## Deliverables

- Deploy-able code with instructions on running service
- Service allow's validator to sign transactions for collectUnlock
- Service allow's relay of BurnQuorum to parent bridge

## Funding Circle

Nervos

## Bounty Owner/Gardener

@mwaa as LeadLink

## Roles
bounty gardener: @mwaa / 50 DAI @johannbarbie / 50 DAI 
bounty worker: @mwaa / 700 DAI
bounty reviewer: name / 100 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
> Use http calls to relay the transactions from indexer to child chain

This actually requires a signing over a [lock receipt](https://github.com/leapdao/nervos/blob/master/docs/childchain.md#lock).

> Provide an http endpoint to receive burn transcations from childchain

This requires a service to scan for EVM events on the child chain. Once an event has been found, it should be [signed by validators again](https://github.com/leapdao/nervos/blob/master/docs/childchain.md#unlock).

> Provide an http endpoint to query bridge balances from the deposit cell

why is this needed?

> Provide an http endpoint to receive deposit requests from UI

why is this needed?

@mwaa can you help me understand the above points? specifically i don't see how you integrate with the validator wallet. I'm getting the gut feeling that there is no other way but to write this a go module to ethermint, otherwise you can't access the wallet of the validators for signing receipts.

**Comment by mwaa** [comment]
@johannbarbie 

- i have updated the ticket to be precise and and only focus on unlock i.e from childchain to parent. 
- questions on how validators will sign without using go module answered on https://github.com/leapdao/nervos/issues/39#issuecomment-694154967
- removed irrelevant scope

No need for validator to manually sign with wallet as they wouldn't be able to do so for even a minimum of 10TPS. 
Since the contract collects the signatures 2/3 validators would have to collude to have a fraudulent unlock
In such a case then the auditDelay script would come in play

**Comment by mwaa** [comment]
Testing of functionality as been forked out to new ticket #55. 
Ran out of time because initial child chain bridge contract was not relaying events as expected on ethermint.
