### ISSUE TITLE
research ethermint. 

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/nervos#3]
# Bounty
Can cosmos modules be integrated? Does ethermint need to be forked?

## Scope

- Evaluate ethermint on integrating other modules
- Evaluate cosmos modules over solidity contracts for child chain
- Prepare short demo on cosmos module functionalities and capabilities

## Deliverables

- A short demo on cosmos modules, then a new ticket detailing whether to use solidity contracts or cosmos module
- Answer on whether to fork ethermint or we can add modules on top of it. 
- Integrate simple cosmos module to ethermint

## Funding Circle
Nervos

## Roles
bounty gardener: @mwaa  / 50 DAI
bounty worker: @mwaa  / 260 DAI
bounty reviewer: 40 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by mwaa** [comment]
Findings
1. No need to fork ethermint. Childchain does not introduce any additional functionality not provided by the EVM. Ethermint provides functionality to configure the bootstrap node through genesis file. For milestone one no need to fork
2. Cosmos module not needed as ethermint exposes rpc calls that can be used outside the confines of a module. Solidity contracts are used for the childchain and don't require a module. Support to use javascript for bridge service to reduce the language set needed to deliver milestone one to solidity, javascript and rust.
3. Demo not done since we are using rpc calls over http to run the relay service. Any demo for bridge would be preferable on the relay service than for a cosmos module.


Discretion of Reviewer to determine if demo is needed  or down grade to XS without the demo

**Comment by johannbarbie** [comment]
> No need to fork ethermint. Childchain does not introduce any additional functionality not provided by the EVM

this is true for milestone 1, given the fact that we have dropped the precompile and use a static validator set. 
for milestone 2 new modules will need to be integrated into the go-lang ethermint framework (see definition of Config Module, Anchor Module and others in [grant proposal](https://talk.nervos.org/t/ckb-sidechain-framework/4722)

> Discretion of Reviewer to determine if demo is needed as time on bounty exceeded size of ticket or down grade to XS without the demo.

i suggest to to leave the bounty size, but follow up with a simple component diagram or sequence diagram to explain how relay server and ethermintd will be interacting for relay of lock and unlock receipts across the chains. (instead of cosmos module demo).

**Comment by mwaa** [comment]
![Relay Lock interaction](https://user-images.githubusercontent.com/5112468/94242804-42529980-ff1f-11ea-99ee-0d536c310680.jpg)

**Comment by mwaa** [comment]
Done
